In [2]:
import pandas as pd
import psycopg2
import os

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="mimiciv_demo",
    user="postgres",
    password=os.getenv("DB_PWORD")
)

# Create a cursor object to execute SQL queries
cur = conn.cursor()

# Example query to fetch data from a table
cur.execute("SELECT * FROM mimiciv_hosp.patients")
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013        None
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013        None
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09

In [6]:
# Fetch and display the first few rows from mimiciv_hosp.transfers
cur.execute("SELECT * FROM mimiciv_hosp.transfers")
rows = cur.fetchall()
df_transfers = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_transfers.head()

,subject_id,hadm_id,transfer_id,eventtype,careunit,intime,outtime
0,10009049,22995465.0,30030230,discharge,None,2174-05-31 14:21:47,NaT
1,10025612,23403708.0,32533329,discharge,None,2125-10-03 12:25:27,NaT
2,10020786,23488445.0,37922399,discharge,None,2189-06-13 17:25:44,NaT
3,10014078,25809882.0,34694622,discharge,None,2166-08-26 14:49:42,NaT
4,10039831,26924951.0,37155928,discharge,None,2116-01-02 14:35:02,NaT

In [7]:
# Fetch and display the first few rows from mimiciv_hosp.admissions
cur.execute("SELECT * FROM mimiciv_hosp.admissions")
rows = cur.fetchall()
df_admissions = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_admissions.head()

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10004235,24181354,2196-02-24 14:38:00,2196-03-04 14:02:00,NaT,URGENT,P03YMR,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicaid,ENGLISH,SINGLE,BLACK/CAPE VERDEAN,2196-02-24 12:15:00,2196-02-24 17:07:00,0
1,10009628,25926192,2153-09-17 17:08:00,2153-09-25 13:20:00,NaT,URGENT,P41R5N,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,?,MARRIED,HISPANIC/LATINO - PUERTO RICAN,NaT,NaT,0
2,10018081,23983182,2134-08-18 02:02:00,2134-08-23 19:35:00,NaT,URGENT,P233F6,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,WHITE,2134-08-17 16:24:00,2134-08-18 03:15:00,0
3,10006053,22942076,2111-11-13 23:39:00,2111-11-15 17:20:00,2111-11-15 17:20:00,URGENT,P38TI6,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,None,UNKNOWN,NaT,NaT,1
4,10031404,21606243,2113-08-04 18:46:00,2113-08-06 20:57:00,NaT,URGENT,P07HDB,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,NaT,NaT,0

In [8]:
# Fetch and display the first few rows from mimiciv_hosp.emar
cur.execute("SELECT * FROM mimiciv_hosp.emar")
rows = cur.fetchall()
df_emar = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_emar.head()

,subject_id,hadm_id,emar_id,emar_seq,poe_id,pharmacy_id,enter_provider_id,charttime,medication,event_txt,scheduletime,storetime
0,10005909,20199380.0,10005909-74,74,10005909-97,96110427.0,None,2144-10-31 05:56:00,Magnesium Sulfate,None,2144-10-31 05:56:00,2144-10-31 05:56:00
1,10005909,20199380.0,10005909-79,79,10005909-97,96110427.0,None,2144-10-31 08:00:00,Magnesium Sulfate,None,2144-10-31 08:00:00,2144-10-31 08:15:00
2,10008287,22168393.0,10008287-32,32,10008287-58,NaN,P26PKF,2145-09-28 20:15:00,Potassium Chloride Replacement (Critical Care ...,None,2145-09-28 20:15:00,2145-09-28 20:38:00
3,10010471,21322534.0,10010471-33,33,10010471-51,52131847.0,None,2155-05-08 21:45:00,Metoprolol Tartrate,None,2155-05-08 21:45:00,2155-05-08 22:40:00
4,10015272,27993466.0,10015272-31,31,10015272-48,88758875.0,None,2137-06-13 08:36:00,Metoprolol Tartrate,None,2137-06-13 08:36:00,2137-06-13 08:36:00

In [9]:
# Fetch and display the first few rows from mimiciv_hosp.emar_detail
cur.execute("SELECT * FROM mimiciv_hosp.emar_detail")
rows = cur.fetchall()
df_emar_detail = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_emar_detail.head()

,subject_id,emar_id,emar_seq,parent_field_ordinal,administration_type,pharmacy_id,barcode_type,reason_for_no_barcode,complete_dose_not_given,dose_due,...,infusion_rate_unit,route,infusion_complete,completion_interval,new_iv_bag_hung,continued_infusion_in_other_location,restart_interval,side,site,non_formulary_visual_verification
0,10039708,10039708-1750,1750,1.1,None,80400800.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,10015860,10015860-565,565,1.1,None,98178739.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,10005866,10005866-571,571,1.1,None,NaN,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,10014354,10014354-2295,2295,1.1,None,7889909.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,10029291,10029291-140,140,None,IV Infusion,NaN,None,None,None,None,...,None,None,N,None,None,None,PRN,None,None,None