# Loading the data

In [40]:
import pandas as pd
import psycopg2
import os
from dotenv import load_dotenv
import numpy as np

load_dotenv()
password = os.getenv("DB_PWORD")

if password is None:
    raise ValueError("Database password is not set in the environment variables.")

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    host="localhost",
    database="mimiciv_demo",
    user="postgres",
    password=password
)

# Create a cursor object to execute SQL queries
cur = conn.cursor()

# Example query to fetch data from a table
cur.execute("SELECT * FROM mimiciv_hosp.patients")
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013        None
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013        None
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09

# Exploring database architecture and fields

In [9]:
# Fetch and display the first few rows from mimiciv_hosp.transfers
cur.execute("SELECT * FROM mimiciv_hosp.transfers WHERE eventtype != 'discharge' LIMIT 5")
rows = cur.fetchall()
df_transfers = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_transfers.head()

,subject_id,hadm_id,transfer_id,eventtype,careunit,intime,outtime
0,10003046,26048429,31766090,transfer,Med/Surg,2154-01-04 15:19:56,2154-01-09 11:53:26
1,10025612,23403708,39182916,transfer,Med/Surg,2125-09-30 18:54:33,2125-10-03 12:25:27
2,10007928,20338077,33930547,transfer,Med/Surg,2129-04-08 21:02:55,2129-04-11 17:45:53
3,10020944,29974575,39351025,transfer,Medicine,2131-03-08 18:30:38,2131-03-13 17:01:34
4,10029484,20764029,37834930,transfer,Medicine,2160-11-08 21:04:55,2160-11-11 11:40:33

In [5]:
# Fetch and display the first few rows from mimiciv_hosp.admissions
cur.execute("SELECT * FROM mimiciv_hosp.admissions")
rows = cur.fetchall()
df_admissions = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_admissions.head()

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10004235,24181354,2196-02-24 14:38:00,2196-03-04 14:02:00,NaT,URGENT,P03YMR,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicaid,ENGLISH,SINGLE,BLACK/CAPE VERDEAN,2196-02-24 12:15:00,2196-02-24 17:07:00,0
1,10009628,25926192,2153-09-17 17:08:00,2153-09-25 13:20:00,NaT,URGENT,P41R5N,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicaid,?,MARRIED,HISPANIC/LATINO - PUERTO RICAN,NaT,NaT,0
2,10018081,23983182,2134-08-18 02:02:00,2134-08-23 19:35:00,NaT,URGENT,P233F6,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,WHITE,2134-08-17 16:24:00,2134-08-18 03:15:00,0
3,10006053,22942076,2111-11-13 23:39:00,2111-11-15 17:20:00,2111-11-15 17:20:00,URGENT,P38TI6,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,None,UNKNOWN,NaT,NaT,1
4,10031404,21606243,2113-08-04 18:46:00,2113-08-06 20:57:00,NaT,URGENT,P07HDB,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,NaT,NaT,0

In [6]:
# Fetch and display the first few rows from mimiciv_hosp.emar
cur.execute("SELECT * FROM mimiciv_hosp.emar")
rows = cur.fetchall()
df_emar = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_emar.head()

,subject_id,hadm_id,emar_id,emar_seq,poe_id,pharmacy_id,enter_provider_id,charttime,medication,event_txt,scheduletime,storetime
0,10005909,20199380.0,10005909-74,74,10005909-97,96110427.0,None,2144-10-31 05:56:00,Magnesium Sulfate,None,2144-10-31 05:56:00,2144-10-31 05:56:00
1,10005909,20199380.0,10005909-79,79,10005909-97,96110427.0,None,2144-10-31 08:00:00,Magnesium Sulfate,None,2144-10-31 08:00:00,2144-10-31 08:15:00
2,10008287,22168393.0,10008287-32,32,10008287-58,NaN,P26PKF,2145-09-28 20:15:00,Potassium Chloride Replacement (Critical Care ...,None,2145-09-28 20:15:00,2145-09-28 20:38:00
3,10010471,21322534.0,10010471-33,33,10010471-51,52131847.0,None,2155-05-08 21:45:00,Metoprolol Tartrate,None,2155-05-08 21:45:00,2155-05-08 22:40:00
4,10015272,27993466.0,10015272-31,31,10015272-48,88758875.0,None,2137-06-13 08:36:00,Metoprolol Tartrate,None,2137-06-13 08:36:00,2137-06-13 08:36:00

In [9]:
# Fetch and display the first few rows from mimiciv_hosp.emar_detail
cur.execute("SELECT * FROM mimiciv_hosp.emar_detail")
rows = cur.fetchall()
df_emar_detail = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_emar_detail.head()

,subject_id,emar_id,emar_seq,parent_field_ordinal,administration_type,pharmacy_id,barcode_type,reason_for_no_barcode,complete_dose_not_given,dose_due,...,infusion_rate_unit,route,infusion_complete,completion_interval,new_iv_bag_hung,continued_infusion_in_other_location,restart_interval,side,site,non_formulary_visual_verification
0,10039708,10039708-1750,1750,1.1,None,80400800.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,10015860,10015860-565,565,1.1,None,98178739.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,10005866,10005866-571,571,1.1,None,NaN,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,10014354,10014354-2295,2295,1.1,None,7889909.0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,10029291,10029291-140,140,None,IV Infusion,NaN,None,None,None,None,...,None,None,N,None,None,None,PRN,None,None,None

In [7]:
# Fetch and display the first few rows from mimiciv_icu.chartevents
cur.execute("SELECT * FROM mimiciv_icu.chartevents LIMIT 5")
rows = cur.fetchall()
df_chartevents = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_chartevents.head()

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10005817,20626031,32604416,6770,2132-12-16,2132-12-15 23:45:00,225054,On,NaN,None,0
1,10005817,20626031,32604416,6770,2132-12-16,2132-12-15 23:43:00,223769,100,100.0,%,0
2,10005817,20626031,32604416,6770,2132-12-16,2132-12-15 23:47:00,223956,Atrial demand,NaN,None,0
3,10005817,20626031,32604416,6770,2132-12-16,2132-12-15 23:47:00,224866,Yes,NaN,None,0
4,10005817,20626031,32604416,6770,2132-12-16,2132-12-15 23:45:00,227341,No,0.0,None,0

In [8]:
# Fetch and display the first few rows from mimiciv_icu.procedureevents
cur.execute("SELECT * FROM mimiciv_icu.procedureevents LIMIT 5")
rows = cur.fetchall()
df_procedureevents = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_procedureevents.head()

,subject_id,hadm_id,stay_id,caregiver_id,starttime,endtime,storetime,itemid,value,valueuom,...,orderid,linkorderid,ordercategoryname,ordercategorydescription,patientweight,isopenbag,continueinnextdept,statusdescription,originalamount,originalrate
0,10027445,26275841,34499716,10712.0,2142-07-31 01:54:00,2142-08-02 10:44:00,2142-08-02 10:44:00.000,225792,3410.0,min,...,532221,532221,Ventilation,ContinuousProcess,103.0,1,0,FinishedRunning,3410.0,1.0
1,10027445,26275841,34499716,80518.0,2142-07-31 08:18:00,2142-08-03 15:10:00,2142-08-03 15:23:00.000,224263,4732.0,min,...,401769,401769,Invasive Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4732.0,1.0
2,10027445,26275841,34499716,96407.0,2142-07-31 06:00:00,2142-08-03 06:03:00,2142-08-03 08:16:00.000,224275,4323.0,min,...,9714245,9714245,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4323.0,1.0
3,10027445,26275841,34499716,96407.0,2142-07-31 02:00:00,2142-08-03 05:57:00,2142-08-03 08:15:00.000,224275,4557.0,min,...,2870557,2870557,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4557.0,1.0
4,10027445,26275841,34499716,NaN,2142-08-03 08:00:00,2142-08-03 21:06:00,2142-08-03 21:06:00.090,224277,786.0,min,...,4920092,4920092,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,786.0,1.0

In [10]:
# Fetch and display the first few rows from mimiciv_hosp.omr
cur.execute("SELECT * FROM mimiciv_hosp.omr LIMIT 5")
rows = cur.fetchall()
df_omr = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_omr.head()

   subject_id   chartdate  seq_num      result_name result_value
0    10011398  2146-12-01        1  Height (Inches)           63
1    10011398  2147-01-22        1     Weight (Lbs)          127
2    10011398  2146-12-01        1     Weight (Lbs)          135
3    10011398  2147-07-24        1     Weight (Lbs)          136
4    10011398  2147-03-26        1     Weight (Lbs)          136

# Constructing dataframe for department destination assist

In [24]:
# Constructing df for department destination identification

query = """
SELECT ad.hadm_id,
       ad.subject_id,
       ser.prev_service,
       ser.curr_service,
       ser.transfertime,
       tran.transfer_id,
       tran.eventtype,
       tran.careunit,
       tran.intime,
       tran.outtime,
       ad.hospital_expire_flag
FROM mimiciv_hosp.admissions ad
JOIN mimiciv_hosp.services ser
ON ad.hadm_id = ser.hadm_id
JOIN mimiciv_hosp.transfers tran
ON ad.hadm_id = tran.hadm_id
WHERE tran.eventtype = 'transfer'
ORDER BY ad.hadm_id, tran.intime
"""

cur.execute(query)
rows = cur.fetchall()
df_services = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])
df_services.head(10)

,hadm_id,subject_id,prev_service,curr_service,transfertime,transfer_id,eventtype,careunit,intime,outtime,hospital_expire_flag
0,20044587,10023771,None,CSURG,2113-08-25 03:17:43,33177122,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2113-08-25 09:32:41,2113-08-27 16:27:53,0
1,20044587,10023771,None,CSURG,2113-08-25 03:17:43,32853830,transfer,Cardiac Surgery,2113-08-27 16:27:53,2113-08-30 14:19:30,0
2,20192635,10037928,None,MED,2177-09-04 12:06:40,35297811,transfer,Medicine,2177-09-04 12:59:33,2177-09-07 17:42:16,0
3,20199380,10005909,None,VSURG,2144-10-28 23:20:44,33425224,transfer,Med/Surg,2144-10-29 09:16:41,2144-10-29 12:05:08,0
4,20199380,10005909,None,VSURG,2144-10-28 23:20:44,38546788,transfer,PACU,2144-10-29 12:05:08,2144-10-29 23:09:03,0
5,20199380,10005909,None,VSURG,2144-10-28 23:20:44,36496303,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-29 23:09:03,2144-10-30 18:52:43,0
6,20199380,10005909,None,VSURG,2144-10-28 23:20:44,39779939,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-30 18:52:43,2144-11-02 15:24:29,0
7,20214994,10003400,None,SURG,2137-02-24 14:05:00,32407866,transfer,PACU,2137-02-25 19:43:32,2137-02-25 23:37:19,0
8,20214994,10003400,None,SURG,2137-02-24 14:05:00,32128372,transfer,Medical/Surgical Intensive Care Unit (MICU/SICU),2137-02-25 23:37:19,2137-03-07 00:35:27,0
9,20214994,10003400,None,SURG,2137-02-24 14:05:00,31973139,transfer,Medical/Surgical Intensive Care Unit (MICU/SICU),2137-03-07 00:35:27,2137-03-10 21:29:36,0

In [25]:
# Printing the number of records in df_services
print(f"Number of records in df_services: {len(df_services)}")

Number of records in df_services: 535

In [ ]:
# Gathering distinct careunits from df_services
distinct_careunits = df_services['careunit'].unique()

# Creating dictionary with distinct care units as keys and None as default values
careunit_dict = {careunit: None for careunit in distinct_careunits}

# Matching MIMIC-IV careunit names with Keck department and level of care names
careunit_dict[distinct_careunits[0]] = ('Vascular Surgery', 'ICU')
careunit_dict[distinct_careunits[16]] = ('Vascular Surgery', 'MedSurg')
careunit_dict[distinct_careunits[13]] = ('Cardiology - General', 'ICU')
careunit_dict[distinct_careunits[8]] = ('Cardiology - General', 'MedSurg')
careunit_dict[distinct_careunits[19]] = ('Cardiology - General', 'Telemetry')
careunit_dict[distinct_careunits[1]] = ('Cardiac Surgery', 'MedSurg')
careunit_dict[distinct_careunits[12]] = ('Neurology', 'MedSurg')
careunit_dict[distinct_careunits[20]] = ('Neurology', 'Stepdown')
careunit_dict[distinct_careunits[21]] = ('Neurology', 'ICU')
careunit_dict[distinct_careunits[23]] = ('Neurology', 'Telemetry')
careunit_dict[distinct_careunits[14]] = ('Hematology (Med CC)', 'Stepdown')
careunit_dict[distinct_careunits[15]] = ('Hematology (Med CC)', 'Telemetry')
careunit_dict[distinct_careunits[17]] = ('GYN', 'MedSurg')



# Printing careunit_dict in tabulated format
print("Care Unit Information:")
for careunit, services in careunit_dict.items():
    print(f"{careunit}: {services}")

Care Unit Information:
Cardiac Vascular Intensive Care Unit (CVICU): ('Vascular Surgery', 'ICU')
Cardiac Surgery: ('Cardiac Surgery', 'MedSurg')
Medicine: None
Med/Surg: None
PACU: None
Medical/Surgical Intensive Care Unit (MICU/SICU): None
Trauma SICU (TSICU): None
Med/Surg/Trauma: None
Medicine/Cardiology: ('Cardiology - General', 'MedSurg')
Surgical Intensive Care Unit (SICU): None
Transplant: None
Medical Intensive Care Unit (MICU): None
Neurology: ('Neurology', 'MedSurg')
Coronary Care Unit (CCU): ('Cardiology - General', 'ICU')
Hematology/Oncology Intermediate: ('Hematology (Med CC)', 'Stepdown')
Hematology/Oncology: ('Hematology (Med CC)', 'Telemetry')
Vascular: ('Vascular Surgery', 'MedSurg')
Med/Surg/GYN: ('GYN', 'MedSurg')
Discharge Lounge: None
Medicine/Cardiology Intermediate: ('Cardiology - General', 'Telemetry')
Neuro Stepdown: ('Neurology', 'Stepdown')
Neuro Surgical Intensive Care Unit (Neuro SICU): ('Neurology', 'ICU')
Surgery/Trauma: None
Neuro Intermediate: ('Neurology', 'Telemetry')
Emergency Department Observation: None

In [ ]:
# Dropping keys from careunit_dict that have None as value (careunits that have no Keck match)
careunit_dict = {k: v for k, v in careunit_dict.items() if v is not None}

# Filtering out records from df_services that have None value in for careunit in careunit_dict
df_filtered = df_services[df_services['careunit'].isin(careunit_dict.keys())]
print(f"Filtered DataFrame shape: {df_filtered.shape[0]} rows, {df_filtered.shape[1]} columns")

Filtered DataFrame shape: 254 rows, 11 columns

In [39]:
# Replacing careunit names with Keck department names and adding a column for level of care
df_filtered['department'] = df_filtered['careunit'].map(lambda x: careunit_dict[x][0])
df_filtered['level_of_care'] = df_filtered['careunit'].map(lambda x: careunit_dict[x][1])
df_filtered.head()

C:\Users\maxac\AppData\Local\Temp\ipykernel_12076\2661790246.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['department'] = df_filtered['careunit'].map(lambda x: careunit_dict[x][0])
C:\Users\maxac\AppData\Local\Temp\ipykernel_12076\2661790246.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['level_of_care'] = df_filtered['careunit'].map(lambda x: careunit_dict[x][1])

,hadm_id,subject_id,prev_service,curr_service,transfertime,transfer_id,eventtype,careunit,intime,outtime,hospital_expire_flag,department,level_of_care
0,20044587,10023771,None,CSURG,2113-08-25 03:17:43,33177122,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2113-08-25 09:32:41,2113-08-27 16:27:53,0,Vascular Surgery,ICU
1,20044587,10023771,None,CSURG,2113-08-25 03:17:43,32853830,transfer,Cardiac Surgery,2113-08-27 16:27:53,2113-08-30 14:19:30,0,Cardiac Surgery,MedSurg
5,20199380,10005909,None,VSURG,2144-10-28 23:20:44,36496303,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-29 23:09:03,2144-10-30 18:52:43,0,Vascular Surgery,ICU
6,20199380,10005909,None,VSURG,2144-10-28 23:20:44,39779939,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-30 18:52:43,2144-11-02 15:24:29,0,Vascular Surgery,ICU
20,20297618,10019385,None,CMED,2180-02-15 20:28:58,31516307,transfer,Medicine/Cardiology,2180-02-20 20:58:42,2180-02-21 06:34:21,0,Cardiology - General,MedSurg

In [42]:
# Randomly assigning requested level of care to each record
# Level of care must only increase or decrease by one level in the order of ICU-Stepdown-Telemetry-MedSurg
# Valid requested levels based on the current level
adjacent_levels = {
    "ICU": ["Stepdown"],
    "Stepdown": ["ICU", "Telemetry"],
    "Telemetry": ["Stepdown", "MedSurg"],
    "MedSurg": ["Telemetry"]
}

rng = np.random.default_rng(seed=42)

df_filtered["requested_level_of_care"] = df_filtered["level_of_care"].map(
    lambda level: rng.choice(adjacent_levels[level])
)
df_filtered.head()

C:\Users\maxac\AppData\Local\Temp\ipykernel_12076\3783639771.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["requested_level_of_care"] = df_filtered["level_of_care"].map(

,hadm_id,subject_id,prev_service,curr_service,transfertime,transfer_id,eventtype,careunit,intime,outtime,hospital_expire_flag,department,level_of_care,requested_level_of_care
0,20044587,10023771,None,CSURG,2113-08-25 03:17:43,33177122,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2113-08-25 09:32:41,2113-08-27 16:27:53,0,Vascular Surgery,ICU,Stepdown
1,20044587,10023771,None,CSURG,2113-08-25 03:17:43,32853830,transfer,Cardiac Surgery,2113-08-27 16:27:53,2113-08-30 14:19:30,0,Cardiac Surgery,MedSurg,Telemetry
5,20199380,10005909,None,VSURG,2144-10-28 23:20:44,36496303,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-29 23:09:03,2144-10-30 18:52:43,0,Vascular Surgery,ICU,Stepdown
6,20199380,10005909,None,VSURG,2144-10-28 23:20:44,39779939,transfer,Cardiac Vascular Intensive Care Unit (CVICU),2144-10-30 18:52:43,2144-11-02 15:24:29,0,Vascular Surgery,ICU,Stepdown
20,20297618,10019385,None,CMED,2180-02-15 20:28:58,31516307,transfer,Medicine/Cardiology,2180-02-20 20:58:42,2180-02-21 06:34:21,0,Cardiology - General,MedSurg,Telemetry